DROP TABLE IF EXISTS TBL_INSURANCE;
 
CREATE TABLE TBL_INSURANCE (
  insurance_id INT AUTO_INCREMENT  PRIMARY KEY,
  ticket_id INT NOT NULL,
  total_price DOUBLE NOT NULL,
  status VARCHAR(250) NOT NULL,
  insurance_amount DOUBLE NOT NULL
);